version: 1

services:
  - type: web
    name: project
    env: docker
    build:
      dockerfile: project/Dockerfile
      dockerContext: ..
    autoDeploy: true
    envVars:
      - key: ConnectionStrings__DefaultConnection
        value: "Server=sqlserver;Database=CharityDB;User Id=sa;Password=SecureP@ssw0rd123;TrustServerCertificate=true"
    routes:
      - type: plain
        name: project
        serviceId: project
        path: /
    plan: free

 - type: web
    name: sqlserver
    env: docker
    image: mcr.microsoft.com/mssql/server:2022-latest
    envVars:
      - key: SA_PASSWORD
        value: "SecureP@ssw0rd123"
      - key: ACCEPT_EULA
        value: "Y"
    ports:
      - port: 5321
        public: true
    volumes:
      - name: sql_data
        path: /var/opt/mssql

volumes:
  - name: sql_data
