// <auto-generated />
using System;
using Domain.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(CharityDBContext))]
    partial class CharityDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.33")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ChatRoomUser", b =>
                {
                    b.Property<int>("IdChatRoom")
                        .HasColumnType("int")
                        .HasColumnName("idChatRoom");

                    b.Property<int>("IdUser")
                        .HasColumnType("int")
                        .HasColumnName("idUser");

                    b.HasKey("IdChatRoom", "IdUser")
                        .HasName("PK__ChatRoom__44BB3FA4CE323C0C");

                    b.HasIndex("IdUser");

                    b.ToTable("ChatRoomUsers", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Category", b =>
                {
                    b.Property<int>("IdCategory")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idCategory");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCategory"), 1L, 1);

                    b.Property<string>("NameCategory")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nameCategory");

                    b.HasKey("IdCategory")
                        .HasName("PK__Categori__79D361B68C8E87A5");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Domain.Models.ChatRoom", b =>
                {
                    b.Property<int>("IdChatRoom")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idChatRoom");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdChatRoom"), 1L, 1);

                    b.Property<string>("NameRoom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nameRoom");

                    b.HasKey("IdChatRoom")
                        .HasName("PK__ChatRoom__77CA433C661BA18F");

                    b.ToTable("ChatRooms");
                });

            modelBuilder.Entity("Domain.Models.Comment", b =>
                {
                    b.Property<int>("IdComment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idComment");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdComment"), 1L, 1);

                    b.Property<string>("CommentDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("commentDescription");

                    b.Property<DateTime>("DateCommented")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("dateCommented")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("IdCourse")
                        .HasColumnType("int")
                        .HasColumnName("idCourse");

                    b.Property<int?>("IdPost")
                        .HasColumnType("int")
                        .HasColumnName("idPost");

                    b.Property<int>("IdUser")
                        .HasColumnType("int")
                        .HasColumnName("idUser");

                    b.HasKey("IdComment")
                        .HasName("PK__Comments__0370297E0752E848");

                    b.HasIndex("IdCourse");

                    b.HasIndex("IdPost");

                    b.HasIndex("IdUser");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("Domain.Models.CommentMedium", b =>
                {
                    b.Property<int>("IdMedia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idMedia");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMedia"), 1L, 1);

                    b.Property<int>("IdComment")
                        .HasColumnType("int")
                        .HasColumnName("idComment");

                    b.Property<string>("MediaPath")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("mediaPath");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("mediaType");

                    b.HasKey("IdMedia")
                        .HasName("PK__CommentM__28E7F573BE92AB29");

                    b.HasIndex("IdComment");

                    b.ToTable("CommentMedia");
                });

            modelBuilder.Entity("Domain.Models.Course", b =>
                {
                    b.Property<int>("IdCourse")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idCourse");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCourse"), 1L, 1);

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("dateCreated")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<int>("IdCategory")
                        .HasColumnType("int")
                        .HasColumnName("idCategory");

                    b.Property<string>("NameCourse")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nameCourse");

                    b.HasKey("IdCourse")
                        .HasName("PK__Courses__8982E309D74A2CF7");

                    b.HasIndex("IdCategory");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("Domain.Models.CourseMedium", b =>
                {
                    b.Property<int>("IdMedia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idMedia");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMedia"), 1L, 1);

                    b.Property<int>("IdCourse")
                        .HasColumnType("int")
                        .HasColumnName("idCourse");

                    b.Property<int>("IdFile")
                        .HasColumnType("int")
                        .HasColumnName("idFile");

                    b.HasKey("IdMedia")
                        .HasName("PK__CourseMe__28E7F5736E85D76B");

                    b.HasIndex("IdCourse");

                    b.HasIndex("IdFile");

                    b.ToTable("CourseMedia");
                });

            modelBuilder.Entity("Domain.Models.DailyUpdate", b =>
                {
                    b.Property<int>("IdUpdate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idUpdate");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUpdate"), 1L, 1);

                    b.Property<DateTime>("DateOfPosted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("dateOfPosted")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<int>("IdUser")
                        .HasColumnType("int")
                        .HasColumnName("idUser");

                    b.HasKey("IdUpdate")
                        .HasName("PK__DailyUpd__746286B669900875");

                    b.HasIndex("IdUser");

                    b.ToTable("DailyUpdates");
                });

            modelBuilder.Entity("Domain.Models.File", b =>
                {
                    b.Property<int>("IdFile")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idFile");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFile"), 1L, 1);

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("filePath");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("fileSize");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("fileType");

                    b.Property<int?>("IdUser")
                        .HasColumnType("int")
                        .HasColumnName("idUser");

                    b.Property<string>("NameFile")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("nameFile");

                    b.HasKey("IdFile")
                        .HasName("PK__Files__775AFE727130F41E");

                    b.HasIndex("IdUser");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("Domain.Models.FileAccess", b =>
                {
                    b.Property<int>("IdFile")
                        .HasColumnType("int")
                        .HasColumnName("idFile");

                    b.Property<int>("IdUser")
                        .HasColumnType("int")
                        .HasColumnName("idUser");

                    b.Property<string>("AccessType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("accessType");

                    b.HasKey("IdFile", "IdUser")
                        .HasName("PK__FileAcce__442B82EAC0E96196");

                    b.HasIndex("IdUser");

                    b.ToTable("FileAccess", (string)null);
                });

            modelBuilder.Entity("Domain.Models.LikesToCourse", b =>
                {
                    b.Property<int>("IdLike")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idLike");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLike"), 1L, 1);

                    b.Property<int>("IdCourse")
                        .HasColumnType("int")
                        .HasColumnName("idCourse");

                    b.Property<int>("IdUser")
                        .HasColumnType("int")
                        .HasColumnName("idUser");

                    b.HasKey("IdLike")
                        .HasName("PK__LikesToC__1439B24683ABE907");

                    b.HasIndex("IdCourse");

                    b.HasIndex("IdUser");

                    b.ToTable("LikesToCourses");
                });

            modelBuilder.Entity("Domain.Models.LikesToPost", b =>
                {
                    b.Property<int>("IdLike")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idLike");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLike"), 1L, 1);

                    b.Property<int>("IdPost")
                        .HasColumnType("int")
                        .HasColumnName("idPost");

                    b.Property<int>("IdUser")
                        .HasColumnType("int")
                        .HasColumnName("idUser");

                    b.HasKey("IdLike")
                        .HasName("PK__LikesToP__1439B24662FBE768");

                    b.HasIndex("IdPost");

                    b.HasIndex("IdUser");

                    b.ToTable("LikesToPosts");
                });

            modelBuilder.Entity("Domain.Models.Message", b =>
                {
                    b.Property<int>("IdMessage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idMessage");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMessage"), 1L, 1);

                    b.Property<int>("IdRecipient")
                        .HasColumnType("int")
                        .HasColumnName("idRecipient");

                    b.Property<int>("IdSender")
                        .HasColumnType("int")
                        .HasColumnName("idSender");

                    b.Property<string>("MessageText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("messageText");

                    b.Property<DateTime>("SendingDatetime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("sendingDatetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("IdMessage")
                        .HasName("PK__Messages__8D0E911DF9998DDF");

                    b.HasIndex("IdRecipient");

                    b.HasIndex("IdSender");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("Domain.Models.Post", b =>
                {
                    b.Property<int>("IdPost")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idPost");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPost"), 1L, 1);

                    b.Property<DateTime>("DatePosted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("datePosted")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("IdUser")
                        .HasColumnType("int")
                        .HasColumnName("idUser");

                    b.Property<string>("PostContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("postContent");

                    b.Property<string>("PostTitle")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("postTitle");

                    b.HasKey("IdPost")
                        .HasName("PK__Posts__BE0F4FD6F2CAA47A");

                    b.HasIndex("IdUser");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("Domain.Models.PostMedium", b =>
                {
                    b.Property<int>("IdMedia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idMedia");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMedia"), 1L, 1);

                    b.Property<int>("IdFile")
                        .HasColumnType("int")
                        .HasColumnName("idFile");

                    b.Property<int>("IdPost")
                        .HasColumnType("int")
                        .HasColumnName("idPost");

                    b.HasKey("IdMedia")
                        .HasName("PK__PostMedi__28E7F573B8658FAE");

                    b.HasIndex("IdFile");

                    b.HasIndex("IdPost");

                    b.ToTable("PostMedia");
                });

            modelBuilder.Entity("Domain.Models.Profile", b =>
                {
                    b.Property<int>("IdProfile")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idProfile");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProfile"), 1L, 1);

                    b.Property<string>("Biography")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("biography");

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("country");

                    b.Property<int>("IdUser")
                        .HasColumnType("int")
                        .HasColumnName("idUser");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("phoneNumber");

                    b.HasKey("IdProfile")
                        .HasName("PK__Profiles__E5A723F8237547AA");

                    b.HasIndex("IdUser");

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("Domain.Models.Role", b =>
                {
                    b.Property<int>("IdRole")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idRole");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRole"), 1L, 1);

                    b.Property<string>("NameRole")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nameRole");

                    b.HasKey("IdRole")
                        .HasName("PK__Roles__E5045C548C159758");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Domain.Models.User", b =>
                {
                    b.Property<int>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idUser");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUser"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("firstName");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("lastName");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("password");

                    b.Property<int>("Role")
                        .HasColumnType("int")
                        .HasColumnName("role");

                    b.HasKey("IdUser")
                        .HasName("PK__Users__3717C9829BB1CC78");

                    b.HasIndex("Role");

                    b.HasIndex(new[] { "Email" }, "UQ__Users__AB6E61648AC7037C")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Domain.Models.UserLanguage", b =>
                {
                    b.Property<int>("IdUser")
                        .HasColumnType("int")
                        .HasColumnName("idUser");

                    b.Property<string>("Language")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("language");

                    b.HasKey("IdUser", "Language")
                        .HasName("PK__UserLang__A9ED13DFD73F19DD");

                    b.ToTable("UserLanguages");
                });

            modelBuilder.Entity("UsersCourse", b =>
                {
                    b.Property<int>("IdUser")
                        .HasColumnType("int")
                        .HasColumnName("idUser");

                    b.Property<int>("IdCourse")
                        .HasColumnType("int")
                        .HasColumnName("idCourse");

                    b.HasKey("IdUser", "IdCourse")
                        .HasName("PK__UsersCou__BF8FE7B2193D808A");

                    b.HasIndex("IdCourse");

                    b.ToTable("UsersCourses", (string)null);
                });

            modelBuilder.Entity("ChatRoomUser", b =>
                {
                    b.HasOne("Domain.Models.ChatRoom", null)
                        .WithMany()
                        .HasForeignKey("IdChatRoom")
                        .IsRequired()
                        .HasConstraintName("FK__ChatRoomU__idCha__5CD6CB2B");

                    b.HasOne("Domain.Models.User", null)
                        .WithMany()
                        .HasForeignKey("IdUser")
                        .IsRequired()
                        .HasConstraintName("FK__ChatRoomU__idUse__5DCAEF64");
                });

            modelBuilder.Entity("Domain.Models.Comment", b =>
                {
                    b.HasOne("Domain.Models.Course", "IdCourseNavigation")
                        .WithMany("Comments")
                        .HasForeignKey("IdCourse")
                        .HasConstraintName("FK__Comments__idCour__66603565");

                    b.HasOne("Domain.Models.Post", "IdPostNavigation")
                        .WithMany("Comments")
                        .HasForeignKey("IdPost")
                        .HasConstraintName("FK__Comments__idPost__656C112C");

                    b.HasOne("Domain.Models.User", "IdUserNavigation")
                        .WithMany("Comments")
                        .HasForeignKey("IdUser")
                        .IsRequired()
                        .HasConstraintName("FK__Comments__idUser__6477ECF3");

                    b.Navigation("IdCourseNavigation");

                    b.Navigation("IdPostNavigation");

                    b.Navigation("IdUserNavigation");
                });

            modelBuilder.Entity("Domain.Models.CommentMedium", b =>
                {
                    b.HasOne("Domain.Models.Comment", "IdCommentNavigation")
                        .WithMany("CommentMedia")
                        .HasForeignKey("IdComment")
                        .IsRequired()
                        .HasConstraintName("FK__CommentMe__idCom__6A30C649");

                    b.Navigation("IdCommentNavigation");
                });

            modelBuilder.Entity("Domain.Models.Course", b =>
                {
                    b.HasOne("Domain.Models.Category", "IdCategoryNavigation")
                        .WithMany("Courses")
                        .HasForeignKey("IdCategory")
                        .IsRequired()
                        .HasConstraintName("FK__Courses__idCateg__4222D4EF");

                    b.Navigation("IdCategoryNavigation");
                });

            modelBuilder.Entity("Domain.Models.CourseMedium", b =>
                {
                    b.HasOne("Domain.Models.Course", "IdCourseNavigation")
                        .WithMany("CourseMedia")
                        .HasForeignKey("IdCourse")
                        .IsRequired()
                        .HasConstraintName("FK__CourseMed__idCou__49C3F6B7");

                    b.HasOne("Domain.Models.File", "IdFileNavigation")
                        .WithMany("CourseMedia")
                        .HasForeignKey("IdFile")
                        .IsRequired()
                        .HasConstraintName("FK__CourseMed__idFil__4AB81AF0");

                    b.Navigation("IdCourseNavigation");

                    b.Navigation("IdFileNavigation");
                });

            modelBuilder.Entity("Domain.Models.DailyUpdate", b =>
                {
                    b.HasOne("Domain.Models.User", "IdUserNavigation")
                        .WithMany("DailyUpdates")
                        .HasForeignKey("IdUser")
                        .IsRequired()
                        .HasConstraintName("FK__DailyUpda__idUse__75A278F5");

                    b.Navigation("IdUserNavigation");
                });

            modelBuilder.Entity("Domain.Models.File", b =>
                {
                    b.HasOne("Domain.Models.User", "IdUserNavigation")
                        .WithMany("Files")
                        .HasForeignKey("IdUser")
                        .HasConstraintName("FK__Files__idUser__46E78A0C");

                    b.Navigation("IdUserNavigation");
                });

            modelBuilder.Entity("Domain.Models.FileAccess", b =>
                {
                    b.HasOne("Domain.Models.File", "IdFileNavigation")
                        .WithMany("FileAccesses")
                        .HasForeignKey("IdFile")
                        .IsRequired()
                        .HasConstraintName("FK__FileAcces__idFil__5165187F");

                    b.HasOne("Domain.Models.User", "IdUserNavigation")
                        .WithMany("FileAccesses")
                        .HasForeignKey("IdUser")
                        .IsRequired()
                        .HasConstraintName("FK__FileAcces__idUse__52593CB8");

                    b.Navigation("IdFileNavigation");

                    b.Navigation("IdUserNavigation");
                });

            modelBuilder.Entity("Domain.Models.LikesToCourse", b =>
                {
                    b.HasOne("Domain.Models.Course", "IdCourseNavigation")
                        .WithMany("LikesToCourses")
                        .HasForeignKey("IdCourse")
                        .IsRequired()
                        .HasConstraintName("FK__LikesToCo__idCou__6E01572D");

                    b.HasOne("Domain.Models.User", "IdUserNavigation")
                        .WithMany("LikesToCourses")
                        .HasForeignKey("IdUser")
                        .IsRequired()
                        .HasConstraintName("FK__LikesToCo__idUse__6D0D32F4");

                    b.Navigation("IdCourseNavigation");

                    b.Navigation("IdUserNavigation");
                });

            modelBuilder.Entity("Domain.Models.LikesToPost", b =>
                {
                    b.HasOne("Domain.Models.Post", "IdPostNavigation")
                        .WithMany("LikesToPosts")
                        .HasForeignKey("IdPost")
                        .IsRequired()
                        .HasConstraintName("FK__LikesToPo__idPos__71D1E811");

                    b.HasOne("Domain.Models.User", "IdUserNavigation")
                        .WithMany("LikesToPosts")
                        .HasForeignKey("IdUser")
                        .IsRequired()
                        .HasConstraintName("FK__LikesToPo__idUse__70DDC3D8");

                    b.Navigation("IdPostNavigation");

                    b.Navigation("IdUserNavigation");
                });

            modelBuilder.Entity("Domain.Models.Message", b =>
                {
                    b.HasOne("Domain.Models.User", "IdRecipientNavigation")
                        .WithMany("MessageIdRecipientNavigations")
                        .HasForeignKey("IdRecipient")
                        .IsRequired()
                        .HasConstraintName("FK__Messages__idReci__5629CD9C");

                    b.HasOne("Domain.Models.User", "IdSenderNavigation")
                        .WithMany("MessageIdSenderNavigations")
                        .HasForeignKey("IdSender")
                        .IsRequired()
                        .HasConstraintName("FK__Messages__idSend__5535A963");

                    b.Navigation("IdRecipientNavigation");

                    b.Navigation("IdSenderNavigation");
                });

            modelBuilder.Entity("Domain.Models.Post", b =>
                {
                    b.HasOne("Domain.Models.User", "IdUserNavigation")
                        .WithMany("Posts")
                        .HasForeignKey("IdUser")
                        .IsRequired()
                        .HasConstraintName("FK__Posts__idUser__60A75C0F");

                    b.Navigation("IdUserNavigation");
                });

            modelBuilder.Entity("Domain.Models.PostMedium", b =>
                {
                    b.HasOne("Domain.Models.File", "IdFileNavigation")
                        .WithMany("PostMedia")
                        .HasForeignKey("IdFile")
                        .IsRequired()
                        .HasConstraintName("FK__PostMedia__idFil__7C4F7684");

                    b.HasOne("Domain.Models.Post", "IdPostNavigation")
                        .WithMany("PostMedia")
                        .HasForeignKey("IdPost")
                        .IsRequired()
                        .HasConstraintName("FK__PostMedia__idPos__7B5B524B");

                    b.Navigation("IdFileNavigation");

                    b.Navigation("IdPostNavigation");
                });

            modelBuilder.Entity("Domain.Models.Profile", b =>
                {
                    b.HasOne("Domain.Models.User", "IdUserNavigation")
                        .WithMany("Profiles")
                        .HasForeignKey("IdUser")
                        .IsRequired()
                        .HasConstraintName("FK__Profiles__idUser__3D5E1FD2");

                    b.Navigation("IdUserNavigation");
                });

            modelBuilder.Entity("Domain.Models.User", b =>
                {
                    b.HasOne("Domain.Models.Role", "RoleNavigation")
                        .WithMany("Users")
                        .HasForeignKey("Role")
                        .IsRequired()
                        .HasConstraintName("FK__Users__role__3A81B327");

                    b.Navigation("RoleNavigation");
                });

            modelBuilder.Entity("Domain.Models.UserLanguage", b =>
                {
                    b.HasOne("Domain.Models.User", "IdUserNavigation")
                        .WithMany("UserLanguages")
                        .HasForeignKey("IdUser")
                        .IsRequired()
                        .HasConstraintName("FK__UserLangu__idUse__787EE5A0");

                    b.Navigation("IdUserNavigation");
                });

            modelBuilder.Entity("UsersCourse", b =>
                {
                    b.HasOne("Domain.Models.Course", null)
                        .WithMany()
                        .HasForeignKey("IdCourse")
                        .IsRequired()
                        .HasConstraintName("FK__UsersCour__idCou__4E88ABD4");

                    b.HasOne("Domain.Models.User", null)
                        .WithMany()
                        .HasForeignKey("IdUser")
                        .IsRequired()
                        .HasConstraintName("FK__UsersCour__idUse__4D94879B");
                });

            modelBuilder.Entity("Domain.Models.Category", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("Domain.Models.Comment", b =>
                {
                    b.Navigation("CommentMedia");
                });

            modelBuilder.Entity("Domain.Models.Course", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("CourseMedia");

                    b.Navigation("LikesToCourses");
                });

            modelBuilder.Entity("Domain.Models.File", b =>
                {
                    b.Navigation("CourseMedia");

                    b.Navigation("FileAccesses");

                    b.Navigation("PostMedia");
                });

            modelBuilder.Entity("Domain.Models.Post", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("LikesToPosts");

                    b.Navigation("PostMedia");
                });

            modelBuilder.Entity("Domain.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Domain.Models.User", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("DailyUpdates");

                    b.Navigation("FileAccesses");

                    b.Navigation("Files");

                    b.Navigation("LikesToCourses");

                    b.Navigation("LikesToPosts");

                    b.Navigation("MessageIdRecipientNavigations");

                    b.Navigation("MessageIdSenderNavigations");

                    b.Navigation("Posts");

                    b.Navigation("Profiles");

                    b.Navigation("UserLanguages");
                });
#pragma warning restore 612, 618
        }
    }
}
