// <auto-generated />
using System;
using Domain.Models1;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(CharityDB1Context))]
    partial class CharityDB1ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.33")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ChatRoomUser", b =>
                {
                    b.Property<int>("IdChatRoom")
                        .HasColumnType("int")
                        .HasColumnName("idChatRoom");

                    b.Property<int>("IdUser")
                        .HasColumnType("int")
                        .HasColumnName("idUser");

                    b.HasKey("IdChatRoom", "IdUser")
                        .HasName("PK__ChatRoom__44BB3FA4F12D23B6");

                    b.HasIndex("IdUser");

                    b.ToTable("ChatRoomUsers", (string)null);
                });

            modelBuilder.Entity("Domain.Models1.Category", b =>
                {
                    b.Property<int>("IdCategory")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idCategory");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCategory"), 1L, 1);

                    b.Property<string>("NameCategory")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nameCategory");

                    b.HasKey("IdCategory")
                        .HasName("PK__Categori__79D361B66658AB6F");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Domain.Models1.ChatRoom", b =>
                {
                    b.Property<int>("IdChatRoom")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idChatRoom");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdChatRoom"), 1L, 1);

                    b.Property<string>("NameRoom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nameRoom");

                    b.HasKey("IdChatRoom")
                        .HasName("PK__ChatRoom__77CA433CC2B7BAB8");

                    b.ToTable("ChatRooms");
                });

            modelBuilder.Entity("Domain.Models1.Comment", b =>
                {
                    b.Property<int>("IdComment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idComment");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdComment"), 1L, 1);

                    b.Property<string>("CommentDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("commentDescription");

                    b.Property<DateTime>("DateCommented")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("dateCommented")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("IdCourse")
                        .HasColumnType("int")
                        .HasColumnName("idCourse");

                    b.Property<int>("IdUser")
                        .HasColumnType("int")
                        .HasColumnName("idUser");

                    b.HasKey("IdComment")
                        .HasName("PK__Comments__0370297E0ABEC5C6");

                    b.HasIndex("IdCourse");

                    b.HasIndex("IdUser");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("Domain.Models1.CommentMedium", b =>
                {
                    b.Property<int>("IdMedia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idMedia");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMedia"), 1L, 1);

                    b.Property<int>("IdComment")
                        .HasColumnType("int")
                        .HasColumnName("idComment");

                    b.Property<string>("MediaPath")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("mediaPath");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("mediaType");

                    b.HasKey("IdMedia")
                        .HasName("PK__CommentM__28E7F573D44E4F80");

                    b.HasIndex("IdComment");

                    b.ToTable("CommentMedia");
                });

            modelBuilder.Entity("Domain.Models1.Course", b =>
                {
                    b.Property<int>("IdCourse")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idCourse");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCourse"), 1L, 1);

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("dateCreated")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<int>("IdCategory")
                        .HasColumnType("int")
                        .HasColumnName("idCategory");

                    b.Property<string>("NameCourse")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nameCourse");

                    b.HasKey("IdCourse")
                        .HasName("PK__Courses__8982E30961DF5E48");

                    b.HasIndex("IdCategory");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("Domain.Models1.CourseMedium", b =>
                {
                    b.Property<int>("IdMedia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idMedia");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMedia"), 1L, 1);

                    b.Property<int>("IdCourse")
                        .HasColumnType("int")
                        .HasColumnName("idCourse");

                    b.Property<string>("MediaPath")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("mediaPath");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("mediaType");

                    b.HasKey("IdMedia")
                        .HasName("PK__CourseMe__28E7F573E40A01E0");

                    b.HasIndex("IdCourse");

                    b.ToTable("CourseMedia");
                });

            modelBuilder.Entity("Domain.Models1.DailyUpdate", b =>
                {
                    b.Property<int>("IdUpdate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idUpdate");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUpdate"), 1L, 1);

                    b.Property<DateTime>("DateOfPosted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("dateOfPosted")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<int>("IdUser")
                        .HasColumnType("int")
                        .HasColumnName("idUser");

                    b.HasKey("IdUpdate")
                        .HasName("PK__DailyUpd__746286B6DAC2F0C4");

                    b.HasIndex("IdUser");

                    b.ToTable("DailyUpdates");
                });

            modelBuilder.Entity("Domain.Models1.File", b =>
                {
                    b.Property<int>("IdFile")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idFile");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFile"), 1L, 1);

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("filePath");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("fileSize");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("fileType");

                    b.Property<int?>("IdUser")
                        .HasColumnType("int")
                        .HasColumnName("idUser");

                    b.Property<string>("NameFile")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("nameFile");

                    b.HasKey("IdFile")
                        .HasName("PK__Files__775AFE7259179706");

                    b.HasIndex("IdUser");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("Domain.Models1.FileAccess", b =>
                {
                    b.Property<int>("IdFile")
                        .HasColumnType("int")
                        .HasColumnName("idFile");

                    b.Property<int>("IdUser")
                        .HasColumnType("int")
                        .HasColumnName("idUser");

                    b.Property<string>("AccessType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("accessType");

                    b.HasKey("IdFile", "IdUser")
                        .HasName("PK__FileAcce__442B82EAE6C122D2");

                    b.HasIndex("IdUser");

                    b.ToTable("FileAccess", (string)null);
                });

            modelBuilder.Entity("Domain.Models1.LikesToCourse", b =>
                {
                    b.Property<int>("IdLike")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idLike");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLike"), 1L, 1);

                    b.Property<int>("IdCourse")
                        .HasColumnType("int")
                        .HasColumnName("idCourse");

                    b.Property<int>("IdUser")
                        .HasColumnType("int")
                        .HasColumnName("idUser");

                    b.HasKey("IdLike")
                        .HasName("PK__LikesToC__1439B246B72B83BF");

                    b.HasIndex("IdCourse");

                    b.HasIndex("IdUser");

                    b.ToTable("LikesToCourses");
                });

            modelBuilder.Entity("Domain.Models1.LikesToPost", b =>
                {
                    b.Property<int>("IdLike")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idLike");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLike"), 1L, 1);

                    b.Property<int>("IdPost")
                        .HasColumnType("int")
                        .HasColumnName("idPost");

                    b.Property<int>("IdUser")
                        .HasColumnType("int")
                        .HasColumnName("idUser");

                    b.HasKey("IdLike")
                        .HasName("PK__LikesToP__1439B246CC281A01");

                    b.HasIndex("IdPost");

                    b.HasIndex("IdUser");

                    b.ToTable("LikesToPosts");
                });

            modelBuilder.Entity("Domain.Models1.Message", b =>
                {
                    b.Property<int>("IdMessage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idMessage");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMessage"), 1L, 1);

                    b.Property<int>("IdRecipient")
                        .HasColumnType("int")
                        .HasColumnName("idRecipient");

                    b.Property<int>("IdSender")
                        .HasColumnType("int")
                        .HasColumnName("idSender");

                    b.Property<string>("MessageText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("messageText");

                    b.Property<DateTime>("SendingDatetime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("sendingDatetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("IdMessage")
                        .HasName("PK__Messages__8D0E911DFE42BF3C");

                    b.HasIndex("IdRecipient");

                    b.HasIndex("IdSender");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("Domain.Models1.Post", b =>
                {
                    b.Property<int>("IdPost")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idPost");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPost"), 1L, 1);

                    b.Property<DateTime>("DatePosted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("datePosted")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("IdUser")
                        .HasColumnType("int")
                        .HasColumnName("idUser");

                    b.Property<string>("PostContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("postContent");

                    b.Property<string>("PostTitle")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("postTitle");

                    b.HasKey("IdPost")
                        .HasName("PK__Posts__BE0F4FD6AC87745C");

                    b.HasIndex("IdUser");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("Domain.Models1.PostMedium", b =>
                {
                    b.Property<int>("IdMedia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idMedia");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMedia"), 1L, 1);

                    b.Property<int>("IdPost")
                        .HasColumnType("int")
                        .HasColumnName("idPost");

                    b.Property<string>("MediaPath")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("mediaPath");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("mediaType");

                    b.HasKey("IdMedia")
                        .HasName("PK__PostMedi__28E7F573F004C291");

                    b.HasIndex("IdPost");

                    b.ToTable("PostMedia");
                });

            modelBuilder.Entity("Domain.Models1.Profile", b =>
                {
                    b.Property<int>("IdProfile")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idProfile");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProfile"), 1L, 1);

                    b.Property<string>("Biography")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("biography");

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("country");

                    b.Property<int>("IdUser")
                        .HasColumnType("int")
                        .HasColumnName("idUser");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("phoneNumber");

                    b.HasKey("IdProfile")
                        .HasName("PK__Profiles__E5A723F880013653");

                    b.HasIndex("IdUser");

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("Domain.Models1.Role", b =>
                {
                    b.Property<int>("IdRole")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idRole");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRole"), 1L, 1);

                    b.Property<string>("NameRole")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nameRole");

                    b.HasKey("IdRole")
                        .HasName("PK__Roles__E5045C5439B472F6");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Domain.Models1.User", b =>
                {
                    b.Property<int>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idUser");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUser"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("firstName");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("lastName");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("password");

                    b.Property<int>("Role")
                        .HasColumnType("int")
                        .HasColumnName("role");

                    b.HasKey("IdUser")
                        .HasName("PK__Users__3717C982D865570F");

                    b.HasIndex("Role");

                    b.HasIndex(new[] { "Email" }, "UQ__Users__AB6E6164854832AF")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Domain.Models1.UserLanguage", b =>
                {
                    b.Property<int>("IdUser")
                        .HasColumnType("int")
                        .HasColumnName("idUser");

                    b.Property<string>("Language")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("language");

                    b.HasKey("IdUser", "Language")
                        .HasName("PK__UserLang__A9ED13DF9D5DBED2");

                    b.ToTable("UserLanguages");
                });

            modelBuilder.Entity("UsersCourse", b =>
                {
                    b.Property<int>("IdUser")
                        .HasColumnType("int")
                        .HasColumnName("idUser");

                    b.Property<int>("IdCourse")
                        .HasColumnType("int")
                        .HasColumnName("idCourse");

                    b.HasKey("IdUser", "IdCourse")
                        .HasName("PK__UsersCou__BF8FE7B2CBA35C98");

                    b.HasIndex("IdCourse");

                    b.ToTable("UsersCourses", (string)null);
                });

            modelBuilder.Entity("ChatRoomUser", b =>
                {
                    b.HasOne("Domain.Models1.ChatRoom", null)
                        .WithMany()
                        .HasForeignKey("IdChatRoom")
                        .IsRequired()
                        .HasConstraintName("FK__ChatRoomU__idCha__5BE2A6F2");

                    b.HasOne("Domain.Models1.User", null)
                        .WithMany()
                        .HasForeignKey("IdUser")
                        .IsRequired()
                        .HasConstraintName("FK__ChatRoomU__idUse__5CD6CB2B");
                });

            modelBuilder.Entity("Domain.Models1.Comment", b =>
                {
                    b.HasOne("Domain.Models1.Course", "IdCourseNavigation")
                        .WithMany("Comments")
                        .HasForeignKey("IdCourse")
                        .IsRequired()
                        .HasConstraintName("FK__Comments__idCour__60A75C0F");

                    b.HasOne("Domain.Models1.User", "IdUserNavigation")
                        .WithMany("Comments")
                        .HasForeignKey("IdUser")
                        .IsRequired()
                        .HasConstraintName("FK__Comments__idUser__5FB337D6");

                    b.Navigation("IdCourseNavigation");

                    b.Navigation("IdUserNavigation");
                });

            modelBuilder.Entity("Domain.Models1.CommentMedium", b =>
                {
                    b.HasOne("Domain.Models1.Comment", "IdCommentNavigation")
                        .WithMany("CommentMedia")
                        .HasForeignKey("IdComment")
                        .IsRequired()
                        .HasConstraintName("FK__CommentMe__idCom__6477ECF3");

                    b.Navigation("IdCommentNavigation");
                });

            modelBuilder.Entity("Domain.Models1.Course", b =>
                {
                    b.HasOne("Domain.Models1.Category", "IdCategoryNavigation")
                        .WithMany("Courses")
                        .HasForeignKey("IdCategory")
                        .IsRequired()
                        .HasConstraintName("FK__Courses__idCateg__4222D4EF");

                    b.Navigation("IdCategoryNavigation");
                });

            modelBuilder.Entity("Domain.Models1.CourseMedium", b =>
                {
                    b.HasOne("Domain.Models1.Course", "IdCourseNavigation")
                        .WithMany("CourseMedia")
                        .HasForeignKey("IdCourse")
                        .IsRequired()
                        .HasConstraintName("FK__CourseMed__idCou__45F365D3");

                    b.Navigation("IdCourseNavigation");
                });

            modelBuilder.Entity("Domain.Models1.DailyUpdate", b =>
                {
                    b.HasOne("Domain.Models1.User", "IdUserNavigation")
                        .WithMany("DailyUpdates")
                        .HasForeignKey("IdUser")
                        .IsRequired()
                        .HasConstraintName("FK__DailyUpda__idUse__73BA3083");

                    b.Navigation("IdUserNavigation");
                });

            modelBuilder.Entity("Domain.Models1.File", b =>
                {
                    b.HasOne("Domain.Models1.User", "IdUserNavigation")
                        .WithMany("Files")
                        .HasForeignKey("IdUser")
                        .HasConstraintName("FK__Files__idUser__4D94879B");

                    b.Navigation("IdUserNavigation");
                });

            modelBuilder.Entity("Domain.Models1.FileAccess", b =>
                {
                    b.HasOne("Domain.Models1.File", "IdFileNavigation")
                        .WithMany("FileAccesses")
                        .HasForeignKey("IdFile")
                        .IsRequired()
                        .HasConstraintName("FK__FileAcces__idFil__5070F446");

                    b.HasOne("Domain.Models1.User", "IdUserNavigation")
                        .WithMany("FileAccesses")
                        .HasForeignKey("IdUser")
                        .IsRequired()
                        .HasConstraintName("FK__FileAcces__idUse__5165187F");

                    b.Navigation("IdFileNavigation");

                    b.Navigation("IdUserNavigation");
                });

            modelBuilder.Entity("Domain.Models1.LikesToCourse", b =>
                {
                    b.HasOne("Domain.Models1.Course", "IdCourseNavigation")
                        .WithMany("LikesToCourses")
                        .HasForeignKey("IdCourse")
                        .IsRequired()
                        .HasConstraintName("FK__LikesToCo__idCou__68487DD7");

                    b.HasOne("Domain.Models1.User", "IdUserNavigation")
                        .WithMany("LikesToCourses")
                        .HasForeignKey("IdUser")
                        .IsRequired()
                        .HasConstraintName("FK__LikesToCo__idUse__6754599E");

                    b.Navigation("IdCourseNavigation");

                    b.Navigation("IdUserNavigation");
                });

            modelBuilder.Entity("Domain.Models1.LikesToPost", b =>
                {
                    b.HasOne("Domain.Models1.Post", "IdPostNavigation")
                        .WithMany("LikesToPosts")
                        .HasForeignKey("IdPost")
                        .IsRequired()
                        .HasConstraintName("FK__LikesToPo__idPos__6FE99F9F");

                    b.HasOne("Domain.Models1.User", "IdUserNavigation")
                        .WithMany("LikesToPosts")
                        .HasForeignKey("IdUser")
                        .IsRequired()
                        .HasConstraintName("FK__LikesToPo__idUse__6EF57B66");

                    b.Navigation("IdPostNavigation");

                    b.Navigation("IdUserNavigation");
                });

            modelBuilder.Entity("Domain.Models1.Message", b =>
                {
                    b.HasOne("Domain.Models1.User", "IdRecipientNavigation")
                        .WithMany("MessageIdRecipientNavigations")
                        .HasForeignKey("IdRecipient")
                        .IsRequired()
                        .HasConstraintName("FK__Messages__idReci__5535A963");

                    b.HasOne("Domain.Models1.User", "IdSenderNavigation")
                        .WithMany("MessageIdSenderNavigations")
                        .HasForeignKey("IdSender")
                        .IsRequired()
                        .HasConstraintName("FK__Messages__idSend__5441852A");

                    b.Navigation("IdRecipientNavigation");

                    b.Navigation("IdSenderNavigation");
                });

            modelBuilder.Entity("Domain.Models1.Post", b =>
                {
                    b.HasOne("Domain.Models1.User", "IdUserNavigation")
                        .WithMany("Posts")
                        .HasForeignKey("IdUser")
                        .IsRequired()
                        .HasConstraintName("FK__Posts__idUser__6B24EA82");

                    b.Navigation("IdUserNavigation");
                });

            modelBuilder.Entity("Domain.Models1.PostMedium", b =>
                {
                    b.HasOne("Domain.Models1.Post", "IdPostNavigation")
                        .WithMany("PostMedia")
                        .HasForeignKey("IdPost")
                        .IsRequired()
                        .HasConstraintName("FK__PostMedia__idPos__797309D9");

                    b.Navigation("IdPostNavigation");
                });

            modelBuilder.Entity("Domain.Models1.Profile", b =>
                {
                    b.HasOne("Domain.Models1.User", "IdUserNavigation")
                        .WithMany("Profiles")
                        .HasForeignKey("IdUser")
                        .IsRequired()
                        .HasConstraintName("FK__Profiles__idUser__3D5E1FD2");

                    b.Navigation("IdUserNavigation");
                });

            modelBuilder.Entity("Domain.Models1.User", b =>
                {
                    b.HasOne("Domain.Models1.Role", "RoleNavigation")
                        .WithMany("Users")
                        .HasForeignKey("Role")
                        .IsRequired()
                        .HasConstraintName("FK__Users__role__3A81B327");

                    b.Navigation("RoleNavigation");
                });

            modelBuilder.Entity("Domain.Models1.UserLanguage", b =>
                {
                    b.HasOne("Domain.Models1.User", "IdUserNavigation")
                        .WithMany("UserLanguages")
                        .HasForeignKey("IdUser")
                        .IsRequired()
                        .HasConstraintName("FK__UserLangu__idUse__76969D2E");

                    b.Navigation("IdUserNavigation");
                });

            modelBuilder.Entity("UsersCourse", b =>
                {
                    b.HasOne("Domain.Models1.Course", null)
                        .WithMany()
                        .HasForeignKey("IdCourse")
                        .IsRequired()
                        .HasConstraintName("FK__UsersCour__idCou__49C3F6B7");

                    b.HasOne("Domain.Models1.User", null)
                        .WithMany()
                        .HasForeignKey("IdUser")
                        .IsRequired()
                        .HasConstraintName("FK__UsersCour__idUse__48CFD27E");
                });

            modelBuilder.Entity("Domain.Models1.Category", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("Domain.Models1.Comment", b =>
                {
                    b.Navigation("CommentMedia");
                });

            modelBuilder.Entity("Domain.Models1.Course", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("CourseMedia");

                    b.Navigation("LikesToCourses");
                });

            modelBuilder.Entity("Domain.Models1.File", b =>
                {
                    b.Navigation("FileAccesses");
                });

            modelBuilder.Entity("Domain.Models1.Post", b =>
                {
                    b.Navigation("LikesToPosts");

                    b.Navigation("PostMedia");
                });

            modelBuilder.Entity("Domain.Models1.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Domain.Models1.User", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("DailyUpdates");

                    b.Navigation("FileAccesses");

                    b.Navigation("Files");

                    b.Navigation("LikesToCourses");

                    b.Navigation("LikesToPosts");

                    b.Navigation("MessageIdRecipientNavigations");

                    b.Navigation("MessageIdSenderNavigations");

                    b.Navigation("Posts");

                    b.Navigation("Profiles");

                    b.Navigation("UserLanguages");
                });
#pragma warning restore 612, 618
        }
    }
}
